# SPDX-FileCopyrightText: 2024 Philip Molares <philip.molares@udo.edu>
#
# SPDX-License-Identifier: MIT

name: Build

on:
  push:
    branches: [ main ]
    paths: ['src/**']
  pull_request:
    branches: [ main ]
    paths: ['src/**']

jobs:
  format:
    name: build
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        - name: Setup rust
          uses: ./.github/actions/setup-rust
          with:
            RUST_VERSION: stable
        - name: Run build
          run: cargo build