# SPDX-FileCopyrightText: 2024 Philip Molares <philip.molares@udo.edu>
#
# SPDX-License-Identifier: MIT

name: Publish Post
on:
  schedule:
    - cron: "30 12 * * *"
  workflow_dispatch:

jobs:
  post:
    name: post
    runs-on: ubuntu-latest
    steps:
      - uses: robinraju/release-downloader@v1.9
        with:
          latest: true
          fileName: "daily_scry"
      - run: chmod +x ./daily_scry
      - name: Run daily_scry
        run: ./daily_scry --mastodon --telegram
        env:
          DAILY_SCRY_MASTODON_URL: ${{ vars.MASTODON_URL }}
          DAILY_SCRY_MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          DAILY_SCRY_TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          DAILY_SCRY_TELEGRAM_CHAT_ID: ${{ vars.TELEGRAM_CHAT_ID }}
