# SPDX-FileCopyrightText: 2024 Philip Molares <philip.molares@udo.edu>
#
# SPDX-License-Identifier: MIT

name: Post a random Magic the Gathering card to telegram and mastodon
on:
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch:

jobs:
  format:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: robinraju/release-downloader@v1.9
        with:
          latest: true
          fileName: "daily_scry"
      - name: Run daily_scry
        run: daily_scry --mastodon --telegram
        env:
          DAILY_SCRY_MASTODON_URL: "{{ secrets.MASTODON_URL }}"
          DAILY_SCRY_MASTODON_ACCESS_TOKEN: "{{ secrets.MASTODON_ACCESS_TOKEN }}"
          DAILY_SCRY_TELEGRAM_TOKEN: "{{ secrets.TELEGRAM_TOKEN }}"
          DAILY_SCRY_TELEGRAM_CHAT_ID: "{{ secrets.TELEGRAM_CHAT_ID }}"
