# SPDX-FileCopyrightText: 2024 Philip Molares <philip.molares@udo.edu>
#
# SPDX-License-Identifier: MIT

name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        - name: Setup rust
          uses: ./.github/actions/setup-rust
          with:
            RUST_VERSION: stable
            RUST_COMPONENTS: rustfmt
        - name: run check fmt
          run: cargo fmt --check