# SPDX-FileCopyrightText: 2024 Philip Molares <philip.molares@udo.edu>
#
# SPDX-License-Identifier: MIT

name: REUSE Compliance Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  reuse:
    runs-on: ubuntu-latest
    container:
      image: fsfe/reuse:3.0.1@sha256:f17b4bea47ee3cad4e2f9a72468b95e0f63c02bc89600dc3445b3c387685e2c8
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Run linter
        run: reuse lint