# SPDX-FileCopyrightText: 2024 Philip Molares <philip.molares@udo.edu>
#
# SPDX-License-Identifier: MIT

name: REUSE Compliance Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  reuse:
    runs-on: ubuntu-latest
    container:
      image: fsfe/reuse:3.0.2@sha256:985ca841881779fa56560cd8478821270e78e4f23e21d7d741370a4abba3c654
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Run linter
        run: reuse lint