# SPDX-FileCopyrightText: 2024 Philip Molares <philip.molares@udo.edu>
#
# SPDX-License-Identifier: MIT

name: Test

on:
  push:
    branches: [ main ]
    paths: ['src/**']
  pull_request:
    branches: [ main ]
    paths: ['src/**']

jobs:
  format:
    name: test
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        - name: Setup rust
          uses: ./.github/actions/setup-rust
          with:
            RUST_VERSION: stable
        - name: Run tests
          run: cargo test