# SPDX-FileCopyrightText: 2024 Philip Molares <philip.molares@udo.edu>
#
# SPDX-License-Identifier: MIT

name: Test

on:
  push:
    branches: [ main ]
    paths: ['src/**']
  pull_request:
    branches: [ main ]
    paths: ['src/**']

jobs:
  format:
    name: test
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        - name: Setup rust
          uses: ./.github/actions/setup-rust
          with:
            RUST_VERSION: stable
        - name: Run tests
          run: cargo test