# SPDX-FileCopyrightText: 2024 Philip Molares <philip.molares@udo.edu>
#
# SPDX-License-Identifier: MIT

name: Test

on:
  push:
    branches: [ main ]
    paths: ['src/**']
  pull_request:
    branches: [ main ]
    paths: ['src/**']

jobs:
  format:
    name: test
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        - name: Setup rust
          uses: ./.github/actions/setup-rust
          with:
            RUST_VERSION: stable
        - name: Run tests
          run: cargo test